version: '3'
services:
  site:
    container_name: site
    image: site
    # restart: always
    build: .
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3001:3001
      - 127.0.0.1:4001:4001
    links:
      - mongo
    volumes:
      - .:/app
    command: sh -c "cd /app && npm i --save --legacy-peer-deps && npm run dev"
    stdin_open: true
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27018'
